### ISSUE TITLE
Is mujoco_py not available?

### ISSUE THREAD

**Issue by jiho314** [ZhengyiLuo/UHC#31]
I'm trying to run the process_amass_db.py after running process_amass_raw.py.

I tried everything but below code brings various errors.
Is mujoco-py unavailable now due to the new mujoco 3.0?

```
from mujoco_py import load_model_from_path
```

error1 : fixed by downgrading cython
```
Cython.Compiler.Errors.CompileError: /home/qkrwlgh0314/miniconda3/envs/uhc-new/lib/python3.8/site-packages/mujoco_py/cymj.pyx
```

error2:  
 i've tried various gcc versions but failed to fix the error
```
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/home/qkrwlgh0314/miniconda3/envs/uhc2/lib/python3.8/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/opt/ohpc/pub/compiler/gcc/8.3.0/bin/gcc' failed with exit code 1

```

**Comment by ZhengyiLuo** [comment]
When using mujoco_py, mujoco 2.1.0 should be downloaded and installed. The first time you run the script mujoco should be built automatically. mujoco 3.0 and mujoco_py are not compatible so it's best not installing them in the same environment. 

For the newest motion imitation & mujoco 3.0 compatibility,  you can refer to [SMPLSim](https://github.com/ZhengyiLuo/SMPLSim) and [PHC_MJX](https://github.com/ZhengyiLuo/PerpetualHumanoidControl_MJX)

**Comment by jiho314** [comment]
Thanks a lot!
