### ISSUE TITLE
Failed to exclude contact between shoulder and chest in IsaacGym

### ISSUE THREAD

**Issue by jjd1123** [ZhengyiLuo/UHC#32]
Hello, I am trying to train an imitation model with a self-collision check in IsaacGym. I used the `smpl_local_robot.py` script you provided to create a humanoid with <exclude> tag. However, I found that the <exclude> tag in mjcf file is useless, like the following:
![image](https://github.com/ZhengyiLuo/UHC/assets/81767877/4d313db5-86b1-4757-b3c1-37581eac5f5f)
Do you have any idea about how to slove it? Thank you very much!

**Comment by ZhengyiLuo** [comment]
HI! Please refer to [PHC](https://github.com/ZhengyiLuo/PHC)'s codebase directly for how to resolve this issue.

**Comment by jjd1123** [comment]
Thank you very much! I will refer to the codebase for the solution. By the way, have you tested whether IsaacGym can exclude contact between certain bodies?

**Comment by jjd1123** [comment]
I finally settled it down by manually setting collision filter of the actor following the code [Here](https://github.com/ZhengyiLuo/PHC/blob/148fa629195f03fe1fa8c0635efe3562faac163e/phc/env/tasks/humanoid.py#L1008) in your other repository [PHC](https://github.com/ZhengyiLuo/PHC). Thanks for your patience!
